# Generated by Django 3.1.6 on 2021-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0002_kategorimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ÜrünModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ürün_adı', models.CharField(max_length=20)),
                ('fiyat', models.IntegerField()),
                ('stok_adet', models.IntegerField()),
                ('kategori', models.ManyToManyField(related_name='ürünler', to='uygulama.KategoriModel')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'ürün',
            },
        ),
    ]
