# Generated by Django 3.1.6 on 2021-02-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0003_ürünmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ürünmodel',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='ürün_resimleri'),
        ),
    ]
