# Generated by Django 3.1.6 on 2021-02-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0005_sparişmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparişmodel',
            name='ürün',
        ),
        migrations.AddField(
            model_name='sparişmodel',
            name='ürün_adı',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sparişler', to='uygulama.ürünmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ürünmodel',
            name='ürün_adı',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
